[package]
name = "seattle-crime"
version = "0.1.0"
authors = ["Andres <andresnrx@gmail.com>"]

[dependencies]
rocket = "0.4.0-rc.1"
reqwest = "0.9"
geojson = "0.12"
geo = "0.10"
chrono = "0.4"
geo-types = "0.2"

[dependencies.rocket_contrib]
version = "0.4.0-rc.1"
default-features = false
features = ["json"]

[dependencies.serde]
version = "1.0"
features = ["serde_derive"]

[dev-dependencies]
mockito = "0.13"
url = "1.7"
serde_urlencoded = "0.5"
mocktopus = "0.5"
serde_json = "1.0"
approx = "0.3"

[features]
default = []
integration = []