[package]
name = "seattle-crime"
version = "0.1.0"
authors = ["Andres <andresnrx@gmail.com>"]

[dependencies]
rocket = ">=0.3.6"
rocket_codegen = ">=0.3.6"
reqwest = ">=0.8.6"
hyper = "0.11.22"
chrono = ">=0.4.1"

[dev-dependencies]
mockito = ">=0.12.0"
url = ">=1.7.1"

[features]
default = []
contract = []