---
resources:
  - name: resource-web-app
    type: git
    source:
      uri: https://github.com/nrxus/safebus.git
  - name: resource-deploy-web-app
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: {{cf_username}}
      password: {{cf_password}}
      organization: seattle-beach
      space: safebus
      skip_cert_check: false

jobs:
  - name: check-compile
    plan:
      - get: resource-web-app
        trigger: true
      - task: check-compile
        config:
          platform: linux
          inputs:
            - name: resource-web-app
          image_resource:
            type: docker-image
            source:
              repository: rust
              tag: 'latest'
          run:
            dir: resource-web-app
            path: cargo
            args: [build]

  - name: test
    plan:
      - get: resource-web-app
        trigger: true
        passed: [check-compile]
      - aggregate:
        - task: unit-test
          config:
            caches:
              - path: resource-web-app/target
            platform: linux
            inputs:
              - name: resource-web-app
            image_resource:
              type: docker-image
              source:
                repository: rust
                tag: 'latest'
            run:
              dir: resource-web-app
              path: cargo
              args: [test]
        - task: contract-test
          config:
            caches:
              - path: resource-web-app/target
            params:
              SEATTLE_API_KEY: {{seattle_api_key}}
              ONEBUSAWAY_API_KEY: {{onebusaway_api_key}}
            platform: linux
            inputs:
              - name: resource-web-app
            image_resource:
              type: docker-image
              source:
                repository: rust
                tag: 'latest'
            run:
              dir: resource-web-app
              path: cargo
              args: [contract-test]
  - name: job-deploy-app
    serial: true
    plan:
    - get: resource-web-app
      trigger: true
      passed: [test]
    - put: resource-deploy-web-app
      params:
        manifest: resource-web-app/manifest.yml
        path: resource-web-app/
        current_app_name: safebus
        environment_variables:
          SEATTLE_API_KEY: {{seattle_api_key}}
          ONEBUSAWAY_API_KEY: {{onebusaway_api_key}}
